### ISSUE TITLE
Proteger o master para não subir direto para ele

### ISSUE THREAD

**Issue by rafacarlossilver** [wsfeitosa/teste-git-allink#1]
Nas configurações do Git-hub é necessário adicionar as regras de Protected Branch, somente o adm pode fazer isso:

![branches](https://user-images.githubusercontent.com/4370680/56364748-b5ea6600-61c5-11e9-98d1-f0b65212857d.png)

**Comment by rafacarlossilver** [comment]
Configuração sugerida:
![branch2](https://user-images.githubusercontent.com/4370680/56365547-7a509b80-61c7-11e9-8fc5-81f1589884de.png)

**Comment by wsfeitosa** [comment]
Configurações realizadas.
